=== GregoryAlexander77/cfml/other_languages/xml/xsd/base.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- ELEMENT DEFINITIONS -->

	<xs:element name="label" type="xs:string" />
	<xs:element name="description" type="xs:string" />
	
	<xs:element name="baseproperties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" minOccurs="0" maxOccurs="1" />
				<xs:element ref="description" minOccurs="0" maxOccurs="1" />
				<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="label" minOccurs="0" maxOccurs="1" />
							<xs:element ref="description" minOccurs="0" maxOccurs="1" />
						</xs:sequence>
						<xs:attribute ref="name" use="required" />
						<xs:attribute ref="type" use="required" />
						<xs:attribute ref="cfc" />
						<xs:attribute ref="default" />
						<xs:attribute ref="editable" />
						<xs:attribute ref="display" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="label" minOccurs="0" maxOccurs="1" />
							<xs:element ref="description" minOccurs="0" maxOccurs="1" />
						</xs:sequence>
						<xs:attribute ref="name" use="required" />
						<xs:attribute ref="type" use="required" />
						<xs:attribute ref="cfc" use="required" />
						<xs:attribute ref="default" />
						<xs:attribute ref="editable" />
						<xs:attribute ref="display" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="ordering" use="required" />
		</xs:complexType>
	</xs:element>
	

	<!-- ATTRIBUTE DEFINITIONS -->
	<!-- on SOBJ -->
	<xs:attribute name="version" type="xs:boolean" />

	<!-- on SOBJ and PROPERTY -->
	<xs:attribute name="name" type="xs:string" />

	<!-- on (BASE)PROPERTIES -->
	<xs:attribute name="ordering" type="xs:string" />

	<!-- on PROPERTY -->
	<xs:attribute name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="string"/>
				<xs:enumeration value="uuid"/>
				<xs:enumeration value="datetime"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="cfc" type="xs:string" />
	<xs:attribute name="default" type="xs:string" />
	<xs:attribute name="editable" type="xs:boolean" />
	<xs:attribute name="display" type="xs:boolean" />


	<!-- DOC STRCUTURE -->
	<xs:element name="sobj">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="label" minOccurs="0" maxOccurs="1" />
				<xs:element ref="description" minOccurs="0" maxOccurs="1" />
				<xs:element ref="baseproperties" minOccurs="0" maxOccurs="1" />
				<xs:element ref="properties" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute ref="name" />
			<xs:attribute ref="cfc" />
			<xs:attribute ref="version" default="true" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== GregoryAlexander77/cfml/other_languages/xml/xsd/base.xml
<sobj
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="base.xsd"
name="sobj_base" cfc="com.pixl8.sycamore.components.Base" version="false">
	<label><![CDATA[Base]]></label>
	<description><![CDATA[Base component that all other Sycamore components extend]]></description>
	<properties ordering="sobj_id,sobj_created,sobj_modified,ten_id">
		<property name="sobj_id" type="uuid" cfc="com.pixl8.sycamore.components.properties.Uuid" default="SYC_UUID" editable="false" display="true">
			<label><![CDATA[Object ID]]></label>
			<description><![CDATA[Primary key for all obejcts]]></description>
		</property>
		<property name="sobj_created" type="datetime" cfc="com.pixl8.sycamore.components.properties.DateTime" default="SYC_TIMESTAMP" editable="false" display="true">
			<label><![CDATA[Date Created]]></label>
			<description><![CDATA[Date/time object was created]]></description>
		</property>
		<property name="sobj_modified" type="datetime" cfc="com.pixl8.sycamore.components.properties.DateTime" editable="false" display="true">
			<label><![CDATA[Date Last Modified]]></label>
			<description><![CDATA[Date/time object was last modified]]></description>
		</property>
		<property name="ten_id" type="uuid" cfc="com.pixl8.sycamore.components.properties.Uuid" editable="false" display="true">
			<label><![CDATA[Tenant]]></label>
			<description><![CDATA[Tenant object relates to]]></description>
		</property>
	</properties>
</sobj>
